name: Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


permissions:
  contents: write


jobs:
  format-titles:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
          fetch-depth: '0'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: test
      run: |
        ls /

    - name: test2
      run: |
        git status

    - name: Install packages
      run: |
        npm install ncp
        
    - name: Run script to format titles in Markdown files
      run: |
        node scripts/format-markdown.js

    - name: Run script to copy attachments
      run: |
        node scripts/copy-attachments.js

    - name: test3
      run: |
        git status

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5


    - name: test4
      run: |
        git status
